version: 2
sources: 
  - name: raw
    schema: gz_raw_data
    description: greenwez raw data source
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: greenwez sales
        columns:
          - name: orders_id
            tests:
              - unique
              - not_null
        tests:
          #- dbt_utils.unique_combination_columns:
              #combination_of_columns:
               # - orders_id
               # - pdt_id
          - unique:
              column_name: "(orders_id || '-' || products_id)"
      - name: product
        identifier: raw_gz_product
        description: the products of greenws
        columns:
          - name: products_id
            tests:
              - unique
              - not_null
      - name: ship
        identifier: raw_gz_ship
        description: the shipments made by greenwez
        columns:
          - name: orders_id
            tests:
              - unique
              - not_null
                  
    
